<a href="https://colab.research.google.com/github/Prateek2111/numpy/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

In [55]:
import numpy as np

np.array([1,2,3,4])

array([1, 2, 3, 4])

In [4]:
np.array([1,2,3.5])

array([1. , 2. , 3.5])

In [5]:
np.array([1,2.4,"hello"])

array(['1', '2.4', 'hello'], dtype='<U32')

Multi Dimensional Array

In [6]:
np.array([1,2,3])

array([1, 2, 3])

In [7]:
np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Generating Sequence

In [10]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [11]:
np.zeros((4,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [12]:
np.zeros(4)

array([0., 0., 0., 0.])

In [13]:
np.ones(3)

array([1., 1., 1.])

In [14]:
np.linspace(0,1,100)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [5]:
np.random.randn(5)

array([ 0.35080525, -0.66763233, -0.99707233, -0.12391742, -0.14364467])

In [7]:
np.random.randint(10,20,10)

array([10, 17, 15, 18, 15, 17, 11, 14, 16, 16])

Array Attributes

In [13]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.shape)
print(arr.size)
print(arr.dtype)

(3, 3)
9
int64


In [15]:
print(arr.sum())

45


In [17]:
print(arr.min())
print(arr.max())

1
9


In [19]:
print(np.sum(arr, axis = 1))

[ 6 15 24]


Array Reshaping

In [28]:
arr = np.arange(1,31);
arr = arr.reshape(6,5);
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


Array Slicing and Indexing of Vector

In [24]:
arr = np.arange(11,20)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [26]:
arr[0:5:2]

array([11, 13, 15])

Slicing and Indexing of Matrix

In [30]:
arr = np.arange(1,31).reshape(6,5);
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [38]:
slice = arr[3:6,3:6]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [40]:
arr = np.arange(1,13).reshape(3,4);
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [41]:
arr[0:2,1:3]

array([[2, 3],
       [6, 7]])

In [45]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

In [46]:
arr1 + arr2

array([ 7,  9, 11, 13, 15])

In [50]:
arr1 ** arr2

array([      1,     128,    6561,  262144, 9765625])

In [51]:
arr = np.array([1,2,3,4,5])
arr+10

array([11, 12, 13, 14, 15])

In [59]:
a = np.array([[1,2],[3,4]]);
b = np.array([[5,6],[7,8]]);

a@b

array([[19, 22],
       [43, 50]])

In [60]:
a.T

array([[1, 3],
       [2, 4]])

In [63]:
a = np.array([1,2,3,4]);
b = np.array([5,6,7,8]);

np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])